//
//  SkinLogPDFExporter.swift
//  AAINA
//

import UIKit

enum SkinLogPDFExporter {

    static func generate(from entry: SkinLogEntry) -> URL {
        let pageWidth:  CGFloat = 595   // A4 pt width
        let pageHeight: CGFloat = 842
        let margin:     CGFloat = 48

        let fmt = DateFormatter()
        fmt.dateStyle = .long
        fmt.timeStyle = .short
        let dateString = fmt.string(from: entry.date)

        // Compose filename
        let ts    = Int(entry.date.timeIntervalSince1970)
        let fname = "SkinLog_\(ts).pdf"
        let url   = FileManager.default.temporaryDirectory.appendingPathComponent(fname)

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            var y: CGFloat = margin

            // ── Header bar 
            let headerRect = CGRect(x: 0, y: 0, width: pageWidth, height: 70)
            UIColor(red: 0.91, green: 0.62, blue: 0.62, alpha: 1).setFill()
            UIRectFill(headerRect)

            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 22, weight: .bold),
                .foregroundColor: UIColor.white
            ]
            "Skin Report".draw(at: CGPoint(x: margin, y: 22), withAttributes: titleAttrs)
            y = 90

            // ── Date
            draw(label: "Date", value: dateString, x: margin, y: &y, pageWidth: pageWidth, margin: margin)

            // ── Flare-up status
            let flareValue = entry.isFlareUp ? "Yes" : "No"
            draw(label: "Flare-up", value: flareValue, x: margin, y: &y, pageWidth: pageWidth, margin: margin)

            // ── Skin concerns
            if !entry.flareUps.isEmpty {
                draw(label: "Skin Concerns", value: entry.flareUps.joined(separator: ", "),
                     x: margin, y: &y, pageWidth: pageWidth, margin: margin)
            }

            // ── Notes
            if !entry.note.isEmpty {
                y += 12
                drawSectionTitle("Notes", x: margin, y: &y)
                let noteAttrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.systemFont(ofSize: 13),
                    .foregroundColor: UIColor.darkGray
                ]
                let noteRect = CGRect(x: margin, y: y, width: pageWidth - margin * 2, height: 300)
                entry.note.draw(in: noteRect, withAttributes: noteAttrs)
                let noteHeight = entry.note.boundingRect(
                    with: CGSize(width: pageWidth - margin * 2, height: 300),
                    options: .usesLineFragmentOrigin,
                    attributes: noteAttrs,
                    context: nil
                ).height
                y += noteHeight + 16
            }

            // ── Photos
            if !entry.photoFileNames.isEmpty {
                y += 4
                drawSectionTitle("Photos", x: margin, y: &y)
                drawPhotoGrid(
                    fileNames: entry.photoFileNames,
                    x: margin,
                    y: &y,
                    maxWidth: pageWidth - margin * 2,
                    pageHeight: pageHeight,
                    bottomLimit: pageHeight - 70,
                    beginNewPage: {
                        ctx.beginPage()
                        return margin
                    }
                )
            }

            // ── Footer
            let footerY: CGFloat = pageHeight - 40
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10),
                .foregroundColor: UIColor.lightGray
            ]
            "Generated by AAINA · \(dateString)".draw(at: CGPoint(x: margin, y: footerY), withAttributes: footerAttrs)
        }

        try? data.write(to: url)
        return url
    }

    // MARK: - Range report (multiple entries)

    static func generateReport(entries: [SkinLogEntry], from fromDate: Date, to toDate: Date) -> URL {
        let pageWidth:  CGFloat = 595
        let pageHeight: CGFloat = 842
        let margin:     CGFloat = 48
        let accentColor = UIColor(red: 0.91, green: 0.62, blue: 0.62, alpha: 1)
        let roseColor   = UIColor(red: 0.65, green: 0.35, blue: 0.45, alpha: 1)

        let rangeFmt = DateFormatter(); rangeFmt.dateFormat = "d MMM yyyy"
        let entryFmt = DateFormatter(); entryFmt.dateFormat = "d MMM yyyy · h:mm a"
        let genFmt   = DateFormatter(); genFmt.dateStyle = .medium; genFmt.timeStyle = .short

        let sorted = entries.sorted { $0.date < $1.date }
        let ts     = Int(Date().timeIntervalSince1970)
        let url    = FileManager.default.temporaryDirectory
                         .appendingPathComponent("SkinReport_\(ts).pdf")

        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { ctx in

            // ── Cover page ──────────────────────────────────────
            ctx.beginPage()

            let headerRect = CGRect(x: 0, y: 0, width: pageWidth, height: 110)
            accentColor.setFill(); UIRectFill(headerRect)

            "Skin Report".draw(
                at: CGPoint(x: margin, y: 24),
                withAttributes: [.font: UIFont.systemFont(ofSize: 24, weight: .bold),
                                 .foregroundColor: UIColor.white])

            "AAINA".draw(
                at: CGPoint(x: margin, y: 60),
                withAttributes: [.font: UIFont.systemFont(ofSize: 13, weight: .medium),
                                 .foregroundColor: UIColor.white.withAlphaComponent(0.75)])

            var y: CGFloat = 130

            let subAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 13),
                .foregroundColor: roseColor]

            "Period:  \(rangeFmt.string(from: fromDate))  –  \(rangeFmt.string(from: toDate))"
                .draw(at: CGPoint(x: margin, y: y), withAttributes: subAttrs); y += 22
            "\(sorted.count) \(sorted.count == 1 ? "entry" : "entries") recorded"
                .draw(at: CGPoint(x: margin, y: y), withAttributes: subAttrs); y += 36

            accentColor.withAlphaComponent(0.25).setStroke()
            let div = UIBezierPath()
            div.move(to: CGPoint(x: margin, y: y))
            div.addLine(to: CGPoint(x: pageWidth - margin, y: y))
            div.lineWidth = 1; div.stroke(); y += 28

            // ── Entries ─────────────────────────────────────────
            func newPage() -> CGFloat {
                ctx.beginPage()
                let stripRect = CGRect(x: 0, y: 0, width: pageWidth, height: 36)
                accentColor.withAlphaComponent(0.12).setFill(); UIRectFill(stripRect)
                "AAINA Skin Report".draw(
                    at: CGPoint(x: margin, y: 10),
                    withAttributes: [.font: UIFont.systemFont(ofSize: 11, weight: .medium),
                                     .foregroundColor: roseColor])
                return 54
            }

            let noteAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 12),
                .foregroundColor: UIColor.darkGray]

            for entry in sorted {
                let needed = entryEstimate(entry: entry, width: pageWidth - margin * 2)
                if y + needed > pageHeight - 60 { y = newPage() }

                // Card background
                let cardH = needed
                let cardRect = CGRect(x: margin - 10, y: y - 8,
                                      width: pageWidth - (margin - 10) * 2, height: cardH + 16)
                UIColor(red: 0.99, green: 0.95, blue: 0.97, alpha: 1).setFill()
                UIBezierPath(roundedRect: cardRect, cornerRadius: 8).fill()

                // Date
                entryFmt.string(from: entry.date).draw(
                    at: CGPoint(x: margin, y: y),
                    withAttributes: [.font: UIFont.systemFont(ofSize: 11, weight: .semibold),
                                     .foregroundColor: roseColor]); y += 18

                // Title
                if !entry.title.isEmpty {
                    entry.title.draw(
                        at: CGPoint(x: margin, y: y),
                        withAttributes: [.font: UIFont.systemFont(ofSize: 14, weight: .semibold),
                                         .foregroundColor: UIColor.black]); y += 20
                }

                // Flare
                if entry.isFlareUp {
                    "Flare-up day".draw(
                        at: CGPoint(x: margin, y: y),
                        withAttributes: [.font: UIFont.systemFont(ofSize: 12),
                                         .foregroundColor: UIColor(red: 0.8, green: 0.3, blue: 0.3, alpha: 1)])
                    y += 18
                }

                // Concerns
                if !entry.flareUps.isEmpty {
                    "Concerns: \(entry.flareUps.joined(separator: ", "))".draw(
                        at: CGPoint(x: margin, y: y), withAttributes: noteAttrs); y += 18
                }

                // Note
                if !entry.note.isEmpty {
                    let w = pageWidth - margin * 2
                    let noteRect = CGRect(x: margin, y: y, width: w, height: 120)
                    entry.note.draw(in: noteRect, withAttributes: noteAttrs)
                    let h = min(120, entry.note.boundingRect(
                        with: CGSize(width: w, height: 120),
                        options: .usesLineFragmentOrigin,
                        attributes: noteAttrs, context: nil).height)
                    y += h + 4
                }

                // Photos
                if !entry.photoFileNames.isEmpty {
                    drawPhotoGrid(
                        fileNames: entry.photoFileNames,
                        x: margin,
                        y: &y,
                        maxWidth: pageWidth - margin * 2,
                        pageHeight: pageHeight,
                        bottomLimit: pageHeight - 70,
                        thumbSize: CGSize(width: 86, height: 64),
                        spacing: 8,
                        beginNewPage: newPage
                    )
                }

                y += 26
            }

            // Footer
            "Generated by AAINA  ·  \(genFmt.string(from: Date()))".draw(
                at: CGPoint(x: margin, y: pageHeight - 36),
                withAttributes: [.font: UIFont.systemFont(ofSize: 10),
                                 .foregroundColor: UIColor.lightGray])
        }

        try? data.write(to: url)
        return url
    }

    private static func entryEstimate(entry: SkinLogEntry, width: CGFloat) -> CGFloat {
        var h: CGFloat = 18
        if !entry.title.isEmpty { h += 20 }
        if entry.isFlareUp      { h += 18 }
        if !entry.flareUps.isEmpty { h += 18 }
        if !entry.note.isEmpty {
            let attrs: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 12)]
            h += min(120, entry.note.boundingRect(
                with: CGSize(width: width, height: 120),
                options: .usesLineFragmentOrigin, attributes: attrs, context: nil).height) + 4
        }
        if !entry.photoFileNames.isEmpty {
            let columns = 5
            let rows = Int(ceil(Double(entry.photoFileNames.count) / Double(columns)))
            h += CGFloat(rows) * 64 + CGFloat(max(rows - 1, 0)) * 8 + 8
        }
        return h
    }

    // MARK: - Drawing helpers

    private static func draw(label: String, value: String,
                             x: CGFloat, y: inout CGFloat,
                             pageWidth: CGFloat, margin: CGFloat) {
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .semibold),
            .foregroundColor: UIColor(red: 0.65, green: 0.35, blue: 0.45, alpha: 1)
        ]
        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13),
            .foregroundColor: UIColor.darkText
        ]

        label.draw(at: CGPoint(x: x, y: y), withAttributes: labelAttrs)
        y += 18
        value.draw(at: CGPoint(x: x, y: y), withAttributes: valueAttrs)
        y += 22

        // Divider
        UIColor.lightGray.withAlphaComponent(0.3).setStroke()
        let path = UIBezierPath()
        path.move(to: CGPoint(x: x, y: y))
        path.addLine(to: CGPoint(x: pageWidth - margin, y: y))
        path.lineWidth = 0.5
        path.stroke()
        y += 16
    }

    private static func drawSectionTitle(_ title: String, x: CGFloat, y: inout CGFloat) {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .semibold),
            .foregroundColor: UIColor(red: 0.65, green: 0.35, blue: 0.45, alpha: 1)
        ]
        title.draw(at: CGPoint(x: x, y: y), withAttributes: attrs)
        y += 20
    }

    private static func drawPhotoGrid(fileNames: [String],
                                      x: CGFloat,
                                      y: inout CGFloat,
                                      maxWidth: CGFloat,
                                      pageHeight: CGFloat,
                                      bottomLimit: CGFloat,
                                      thumbSize: CGSize = CGSize(width: 110, height: 82),
                                      spacing: CGFloat = 10,
                                      beginNewPage: () -> CGFloat) {
        let images = fileNames.compactMap { JournalPhotoStore.load(named: $0) }
        guard !images.isEmpty else { return }

        let columns = max(1, Int((maxWidth + spacing) / (thumbSize.width + spacing)))
        for (index, image) in images.enumerated() {
            if index > 0 && index % columns == 0 {
                y += thumbSize.height + spacing
            }

            if y + thumbSize.height > bottomLimit {
                y = beginNewPage()
            }

            let column = index % columns
            let thumbX = x + CGFloat(column) * (thumbSize.width + spacing)
            let rect = CGRect(origin: CGPoint(x: thumbX, y: y), size: thumbSize)
            drawRoundedImage(image, in: rect)
        }

        y += thumbSize.height + 10
    }

    private static func drawRoundedImage(_ image: UIImage, in rect: CGRect) {
        guard let cgImage = image.cgImage else { return }

        let path = UIBezierPath(roundedRect: rect, cornerRadius: 8)
        UIColor.white.setFill()
        path.fill()

        UIGraphicsGetCurrentContext()?.saveGState()
        path.addClip()
        image.draw(in: aspectFillRect(for: CGSize(width: cgImage.width, height: cgImage.height), in: rect))
        UIGraphicsGetCurrentContext()?.restoreGState()

        UIColor.white.withAlphaComponent(0.9).setStroke()
        path.lineWidth = 1
        path.stroke()
    }

    private static func aspectFillRect(for imageSize: CGSize, in rect: CGRect) -> CGRect {
        guard imageSize.width > 0, imageSize.height > 0 else { return rect }
        let scale = max(rect.width / imageSize.width, rect.height / imageSize.height)
        let width = imageSize.width * scale
        let height = imageSize.height * scale
        return CGRect(
            x: rect.midX - width / 2,
            y: rect.midY - height / 2,
            width: width,
            height: height
        )
    }
}
